plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: broadcast-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
        - route53:*
        - ec2:*
      Resource: '*'
  environment:
    MONGO_URL: ${env:MONGO_URL}
    JWT_SIGNING_KEY: ${env:JWT_SIGNING_KEY}
    BASE_URL: ${env:BASE_URL, 'https://broadcast.nylund.us'}
    HOSTED_ZONE_ID: ${env:HOSTED_ZONE_ID}
    EC2_ACCESS_KEY_ID: ${env:EC2_ACCESS_KEY_ID}
    EC2_SECRET_ACCESS_KEY: ${env:EC2_SECRET_ACCESS_KEY}
    LAUNCH_TEMPLATE_ID: ${env:LAUNCH_TEMPLATE_ID}
    LAUNCH_TEMPLATE_VERSION: ${env:LAUNCH_TEMPLATE_VERSION}
    RELAY_BUCKET: ${env:RELAY_BUCKET}

functions:
  api:
    handler: src/handler.app
    events:
      - httpApi: '*'
